### ISSUE TITLE
Armazenar e-mail do advogado

### ISSUE THREAD

**Issue by makintoshi** [idvogados/backend#8]
# CONTEXTO/PROPÓSITO
Na página principal (homepage) o advogado indica o seu perfil e resolve um captcha.
O propósito aqui é armazenar o e-mail que o advogado informou no form que é exibido após a resolução do captcha.

# CRITÉRIOS DE ACEITE
1) O formato do e-mail deve ser validado
2) O perfil (advogado) e o e-mail informado por ele devem ser armazenados

**Comment by pictos** [comment]
Fechando essa issue, pois já existe um ticket de desenvolvimento para ela.
